### ISSUE TITLE
Help another thing went wrong!

### ISSUE THREAD

**Issue by ZainKergaye** [cshmookler/My-Online-Portfolio#2]
When I try to run this code with "ONLINE CODE RUN FREE NO HACKS NO CHEAT GET $$$" it has me download some software that took all my bitcoin and doge NFT's. Can I have them back please? I spent my life savings on them! They are one of a kind pieces that are worth over 10.3 dollars.

**Comment by cshmookler** [comment]
Try it again.

**Comment by ZainKergaye** [comment]
I did but it keeps telling me to insert bitcoin into usb slot???
